-- 코드를 작성해주세요

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM SKILLCODES S JOIN DEVELOPERS D ON D.SKILL_CODE & S.CODE  > 0
WHERE S.NAME IN ('Python', 'C#')
ORDER BY ID;

# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
# FROM DEVELOPERS
# WHERE SKILL_CODE & 256 = 256 OR SKILL_CODE & 1024 = 1024
# ORDER BY ID;
